# Generated by Django 4.2.30 on 2026-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='LinkedIn Developer App Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='LinkedIn Developer App Client Secret', max_length=255)),
                ('organization_id', models.CharField(help_text='LinkedIn Organization ID (e.g. 12345678)', max_length=100)),
                ('access_token', models.TextField(blank=True, help_text='OAuth Access Token', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth Refresh Token', null=True)),
                ('expires_in', models.IntegerField(blank=True, help_text='Access token lifetime in seconds', null=True)),
                ('refresh_token_expires_in', models.IntegerField(blank=True, help_text='Refresh token lifetime in seconds', null=True)),
                ('authorized_at', models.DateTimeField(blank=True, help_text='Timestamp when the token was acquired', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LinkedIn Credential',
                'verbose_name_plural': 'LinkedIn Credentials',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='linkedin', max_length=50)),
                ('content', models.TextField(help_text='The body text of the social media post')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Time to publish (if scheduled)', null=True)),
                ('published_time', models.DateTimeField(blank=True, help_text='Actual publish time', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if posting failed', null=True)),
                ('linkedin_post_urn', models.CharField(blank=True, help_text='LinkedIn Post URN reference', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
