# Generated by Django 4.2.30 on 2026-06-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedincredential',
            name='organization_id',
            field=models.CharField(blank=True, help_text="LinkedIn Organization ID (e.g. 12345678) or Person URN (e.g. urn:li:person:XXXX). If empty, the system will use the authenticated user's profile URN.", max_length=100, null=True),
        ),
    ]
