# Generated by Django 4.2.30 on 2026-06-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_linkedincredential_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly slug (e.g. demystifying-dmarc)', max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='A short summary/excerpt of the post shown in listings')),
                ('content', models.TextField(help_text='The full body content of the blog post (supports Markdown/HTML)')),
                ('date', models.CharField(blank=True, help_text='Display date (e.g. June 01, 2026). If blank, will display current date format.', max_length=100)),
                ('author', models.CharField(default='SecureStack Research Team', help_text='Author name and title', max_length=255)),
                ('read_time', models.CharField(default='5 min read', help_text='Estimated read time (e.g. 6 min read)', max_length=50)),
                ('category', models.CharField(default='Cybersecurity', help_text='Category (e.g. Cybersecurity, Development, Cloud & DevOps)', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. Email Security, DMARC, Compliance)', max_length=255)),
                ('seo_title', models.CharField(blank=True, help_text='Optional custom SEO Title tag', max_length=255, null=True)),
                ('seo_desc', models.TextField(blank=True, help_text='Optional custom SEO Meta Description', null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
