# Generated by Django 4.2.30 on 2026-06-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Meta App ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Meta App Secret', max_length=255)),
                ('page_id', models.CharField(help_text='Facebook Page ID (numeric)', max_length=100)),
                ('user_access_token', models.TextField(blank=True, help_text='Long-lived User Access Token', null=True)),
                ('page_access_token', models.TextField(blank=True, help_text='Permanent Page Access Token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facebook Credential',
                'verbose_name_plural': 'Facebook Credentials',
            },
        ),
    ]
