# Generated by Django 4.2.30 on 2026-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
