# Generated by Django 4.2.20 on 2025-03-14 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('A1', 'A1 Farm'), ('A2', 'A2 Farm')], max_length=2)),
                ('gazette_status', models.CharField(choices=[('gazetted', 'Gazetted'), ('not_gazetted', 'Not Gazetted')], max_length=20)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_units', models.CharField(default='hectares', max_length=20)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lims_officer', 'LIMS Officer'), ('estates_officer', 'Estates and Valuations Officer'), ('acquisition_officer', 'Acquisition Officer'), ('resettlement_officer', 'Resettlement Officer')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landsApp.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landsApp.farm')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landsApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FarmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('offer_letter', 'Offer Letter'), ('gazette_notice', 'Gazette Notice'), ('survey_diagram', 'Survey Diagram'), ('valuation_report', 'Valuation Report'), ('other', 'Other')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='farm_documents/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landsApp.farm')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landsApp.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landsApp.userprofile'),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landsApp.farmowner'),
        ),
        migrations.AddField(
            model_name='farm',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landsApp.province'),
        ),
    ]
