# Generated by Django 4.2.20 on 2025-03-19 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_number', models.CharField(max_length=50, unique=True)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_units', models.CharField(default='hectares', max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('allocation_status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_a2farms', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landsApp.province')),
            ],
        ),
        migrations.CreateModel(
            name='A2Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('owner_id_number', models.CharField(max_length=50)),
                ('owner_address', models.TextField()),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('printed', 'Printed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_printing_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_permits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permits', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landsApp.a2farm')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_permits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermitPrintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('print_reason', models.TextField()),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landsApp.a2permit')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
