# Generated by Django 4.2.20 on 2025-03-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0002_a2farm_a2permit_permitprinthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_number', models.CharField(max_length=50)),
                ('subdivision_type', models.CharField(choices=[('A1', 'A1 Subdivision'), ('A2', 'A2 Subdivision')], max_length=2)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_units', models.CharField(default='hectares', max_length=20)),
                ('planned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdivisions', to='landsApp.farm')),
                ('planned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_subdivisions', to='landsApp.userprofile')),
            ],
            options={
                'unique_together': {('parent_farm', 'subdivision_number')},
            },
        ),
    ]
