# Generated by Django 4.2.20 on 2025-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0003_farmsubdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(help_text='Unique identifier for the farm', max_length=20, unique=True)),
                ('farm_name', models.CharField(max_length=255)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area_units', models.CharField(choices=[('hectares', 'Hectares'), ('acres', 'Acres'), ('morgens', 'Morgens'), ('square_meters', 'Square Meters'), ('square_kilometers', 'Square Kilometers')], max_length=20)),
                ('size_hectares', models.DecimalField(decimal_places=2, help_text='Area size converted to hectares', max_digits=15)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('natural_region', models.CharField(max_length=50)),
                ('farm_category', models.CharField(max_length=50)),
                ('title_deed_number', models.CharField(max_length=100)),
                ('title_type', models.CharField(max_length=50)),
                ('gazette_status', models.CharField(max_length=50)),
                ('gazette_date', models.DateField(blank=True, null=True)),
                ('gazette_number', models.CharField(blank=True, max_length=100)),
                ('diagram_number', models.CharField(max_length=100)),
                ('farm_activity', models.CharField(max_length=100)),
                ('ownership', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('is_planned', models.CharField(default='unplanned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parent Farm',
                'verbose_name_plural': 'Parent Farms',
                'ordering': ['farm_name'],
            },
        ),
    ]
