# Generated by Django 4.2.20 on 2025-03-21 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0004_parentfarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfarm',
            name='nationality',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='owner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='gazette_status',
            field=models.CharField(choices=[('gazetted', 'Gazetted'), ('not_gazetted', 'Not Gazetted'), ('pending', 'Pending')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='is_planned',
            field=models.BooleanField(default=False, help_text='Indicates if the farm is planned'),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='ownership',
            field=models.CharField(choices=[('private', 'Private'), ('state', 'State'), ('communal', 'Communal'), ('other', 'Other')], max_length=50),
        ),
    ]
