# Generated by Django 4.2.20 on 2025-03-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0005_parentfarm_nationality_parentfarm_owner_name_and_more'),
        ('landsApp', '0005_populate_parent_farms'),
    ]

    operations = [
    ]
