# Generated by Django 4.2.20 on 2025-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0007_parentfarm_bippa_parentfarm_bippa_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfarm',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes about the farm', null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality of the farm owner', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Name of the farm owner', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='size_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of the farm in hectares', max_digits=10, null=True),
        ),
    ]
