# Generated by Django 5.1.3 on 2025-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0008_parentfarm_remarks_alter_parentfarm_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentfarm',
            name='farm_activity',
        ),
        migrations.RemoveField(
            model_name='parentfarm',
            name='natural_region',
        ),
        migrations.RemoveField(
            model_name='parentfarm',
            name='previous_district',
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='farm_number',
            field=models.IntegerField(default=0, help_text='Enter a number between 0 and 9999'),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='bippa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='bippa_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='bonding_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='bonds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='carvet_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='carvet_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='carvets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='diagram_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='gazette_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='gazette_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='is_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='nationality',
            field=models.CharField(default='YourDefaultValue', max_length=255),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='ownership',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='province',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='servitude_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='servitude_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='servitudes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='size_hectares',
            field=models.DecimalField(decimal_places=2, default=111, editable=False, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='title_deed_number',
            field=models.CharField(max_length=50),
        ),
    ]
