# Generated by Django 5.1.3 on 2025-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0009_remove_parentfarm_farm_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='previous_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='endorsements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='previous_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='gazette_status',
            field=models.CharField(choices=[('gazetted', 'Gazetted'), ('not_gazetted', 'Not Gazetted'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='nationality',
            field=models.CharField(default='Zimbabwean', max_length=255),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='ownership',
            field=models.CharField(choices=[('private', 'Private'), ('state', 'State'), ('communal', 'Communal'), ('other', 'Other')], max_length=20),
        ),
    ]
