# Generated by Django 5.1.3 on 2025-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0010_farm_previous_district_parentfarm_endorsements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfarm',
            name='general_notice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
