# Generated by Django 5.1.3 on 2025-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0011_parentfarm_general_notice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfarm',
            name='farm_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
