# Generated by Django 5.1.3 on 2025-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0012_parentfarm_farm_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfarm',
            name='natural_region',
            field=models.CharField(blank=True, choices=[('1', 'Region 1'), ('2', 'Region 2'), ('3', 'Region 3'), ('4', 'Region 4'), ('5', 'Region 5')], help_text='Natural region of the farm', max_length=50, null=True),
        ),
    ]
