# Generated by Django 5.1.3 on 2025-04-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsApp', '0013_parentfarm_natural_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfarm',
            name='a2_farms',
            field=models.ManyToManyField(blank=True, related_name='parent_farms', to='landsApp.a2farm'),
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='remaining_extent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining area of the farm in hectares', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='state_land',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='State land area in hectares', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='farm_category',
            field=models.CharField(choices=[('A1', 'A1 Farm'), ('A2', 'A2 Farm'), ('both', 'Both A1 and A2 Farms')], default='both', help_text='Category of the farm (A1, A2, or Both)', max_length=10),
        ),
        migrations.AlterField(
            model_name='parentfarm',
            name='is_planned',
            field=models.BooleanField(default=False, help_text='Indicates if the farm has been planned into A1 and A2 farms'),
        ),
        migrations.CreateModel(
            name='A1Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_number', models.CharField(max_length=50, unique=True)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_units', models.CharField(default='hectares', max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landsApp.province')),
            ],
        ),
        migrations.AddField(
            model_name='parentfarm',
            name='a1_farms',
            field=models.ManyToManyField(blank=True, related_name='parent_farms', to='landsApp.a1farm'),
        ),
    ]
