# Generated by Django 4.2.30 on 2026-06-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '__first__'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_leads', to='affiliate.affiliate'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reward_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Enquiry'), ('converted', 'Converted (Project Won)'), ('rejected', 'Rejected / Invalid')], default='pending', max_length=20),
        ),
    ]
